/**
 * Expanded canonical interests and categories for discovery scoring
 * Discovery algorithm maps user interests to these categories to compute compatibility
 * User interests are NOT modified; they're matched as-is against this library
 */

export const CANONICAL_INTERESTS = [
  // Technology & Development (25 interests)
  "Coding",
  "Programming",
  "Web Development",
  "Mobile Development",
  "Frontend Development",
  "Backend Development",
  "Full Stack",
  "Software Engineering",
  "Data Science",
  "Machine Learning",
  "AI",
  "Artificial Intelligence",
  "Cybersecurity",
  "DevOps",
  "Cloud Computing",
  "Tech Startups",
  "App Development",
  "Game Development",
  "VR",
  "Augmented Reality",
  "Blockchain",
  "Open Source",
  "Tech",
  "Technology",
  "Hardware",

  // Gaming & Entertainment (30 interests)
  "Gaming",
  "Video Games",
  "Board Games",
  "Esports",
  "Tabletop Gaming",
  "RPG",
  "Strategy Games",
  "Indie Games",
  "Console Gaming",
  "PC Gaming",
  "Mobile Games",
  "Competitive Gaming",
  "Streaming",
  "Movies",
  "Film",
  "Cinematography",
  "TV Shows",
  "Netflix",
  "Animation",
  "Anime",
  "Manga",
  "Comics",
  "Graphic Novels",
  "Superhero",
  "Sci-Fi",
  "Fantasy",
  "Horror",
  "Comedy",
  "Drama",
  "Action Movies",

  // Creative & Arts (45 interests)
  "Art",
  "Drawing",
  "Painting",
  "Watercolor",
  "Sculpture",
  "Digital Art",
  "Graphic Design",
  "UI Design",
  "UX Design",
  "Web Design",
  "Photography",
  "Portrait Photography",
  "Landscape Photography",
  "Street Photography",
  "Videography",
  "Film Making",
  "Filmography",
  "Video Editing",
  "Music",
  "Singing",
  "Karaoke",
  "Instruments",
  "Piano",
  "Guitar",
  "Bass",
  "Drums",
  "Violin",
  "Music Production",
  "Producing",
  "DJing",
  "Beats",
  "Remix",
  "Writing",
  "Creative Writing",
  "Screenwriting",
  "Storytelling",
  "Blogging",
  "Vlogging",
  "Poetry",
  "Spoken Word",
  "Theater",
  "Acting",
  "Dance",
  "Improv",
  "Stand-up Comedy",

  // Sports & Fitness (48 interests)
  "Fitness",
  "Gym",
  "Strength Training",
  "Weightlifting",
  "CrossFit",
  "HIIT",
  "Running",
  "Marathon",
  "Jogging",
  "Track & Field",
  "Walking",
  "Hiking",
  "Trail Running",
  "Cycling",
  "Mountain Biking",
  "Road Biking",
  "Swimming",
  "Triathlon",
  "Basketball",
  "Soccer",
  "Football",
  "American Football",
  "Rugby",
  "Tennis",
  "Badminton",
  "Volleyball",
  "Beach Volleyball",
  "Baseball",
  "Softball",
  "Cricket",
  "Hockey",
  "Ice Hockey",
  "Field Hockey",
  "Lacrosse",
  "Martial Arts",
  "Karate",
  "Taekwondo",
  "Boxing",
  "Kickboxing",
  "Muay Thai",
  "MMA",
  "Wrestling",
  "Rock Climbing",
  "Bouldering",
  "Skateboarding",
  "Surfing",
  "Wakeboarding",
  "Snowboarding",
  "Skiing",
  "Ice Skating",
  "Gymnastics",
  "Archery",
  "Bowling",

  // Wellness & Mindfulness (28 interests)
  "Yoga",
  "Meditation",
  "Mindfulness",
  "Mental Health",
  "Therapy",
  "Counseling",
  "Pilates",
  "Stretching",
  "Contemporary Dance",
  "Ballet",
  "Hip Hop Dance",
  "Zumba",
  "Aerobics",
  "Wellness",
  "Spa",
  "Aromatherapy",
  "Nutrition",
  "Holistic Health",
  "Acupuncture",
  "Self-Care",
  "Personal Development",
  "Journaling",
  "Sleep Wellness",
  "Energy Work",
  "Chakra Balancing",
  "Breathwork",
  "Detox",
  "Gratitude",

  // Outdoor & Adventure (25 interests)
  "Backpacking",
  "Camping",
  "Glamping",
  "Outdoor Adventures",
  "Travel",
  "Road Trips",
  "Exploring",
  "Nature",
  "Parks",
  "National Parks",
  "Beaches",
  "Mountains",
  "Deserts",
  "Forests",
  "Islands",
  "Fishing",
  "Fly Fishing",
  "Hunting",
  "Kayaking",
  "Canoeing",
  "Paddleboarding",
  "Whitewater Rafting",
  "Adventure Sports",
  "Scuba Diving",
  "Snorkeling",

  // Culinary & Food (35 interests)
  "Cooking",
  "Baking",
  "Pastry",
  "Desserts",
  "Recipe Development",
  "Meal Prep",
  "Foodie",
  "Food Photography",
  "Restaurants",
  "Fine Dining",
  "Michelin Dining",
  "Home Cooking",
  "Home Baking",
  "BBQ",
  "Grilling",
  "Smoking Meats",
  "Sushi",
  "Asian Cuisine",
  "Italian Cooking",
  "Mexican Food",
  "Indian Cuisine",
  "Thai Food",
  "Mediterranean",
  "Vegan",
  "Vegetarian",
  "Gluten-Free",
  "Coffee",
  "Specialty Coffee",
  "Barista",
  "Tea",
  "Bubble Tea",
  "Wine",
  "Wine Tasting",
  "Beer",
  "Craft Beer",
  "Cocktails",
  "Mixology",
  "Brewing",
  "Fermentation",

  // Intellectual & Learning (35 interests)
  "Reading",
  "Books",
  "Fiction",
  "Non-Fiction",
  "Mystery",
  "Thriller",
  "Romance",
  "Historical Fiction",
  "Self-Help",
  "Biography",
  "Memoirs",
  "Science",
  "Physics",
  "Chemistry",
  "Biology",
  "Astronomy",
  "Space",
  "Astrology",
  "History",
  "Ancient History",
  "Medieval History",
  "Philosophy",
  "Ethics",
  "Psychology",
  "Sociology",
  "Economics",
  "Politics",
  "Current Events",
  "News",
  "Languages",
  "Learning",
  "Education",
  "Podcasts",
  "TED Talks",
  "Documentaries",

  // Social & Community (32 interests)
  "Volunteering",
  "Charity",
  "Social Causes",
  "Community Service",
  "Activism",
  "Environmentalism",
  "Sustainability",
  "Climate Change",
  "Social Justice",
  "Mental Health Advocacy",
  "Networking",
  "Making Friends",
  "Leadership",
  "Public Speaking",
  "Mentoring",
  "Coaching",
  "Team Sports",
  "Group Activities",
  "Events",
  "Meetups",
  "Parties",
  "Nightlife",
  "Road Trips with Friends",
  "Group Hiking",
  "Study Groups",
  "Debate",
  "Philosophy Discussions",
  "Book Clubs",
  "Film Clubs",
  "Wine Tasting Groups",
  "Alumni Events",
  "Campus Clubs",

  // Pets & Animals (15 interests)
  "Pets",
  "Dogs",
  "Dog Training",
  "Cats",
  "Cat Care",
  "Birds",
  "Exotic Pets",
  "Fish",
  "Aquariums",
  "Reptiles",
  "Snakes",
  "Animal Rescue",
  "Animal Welfare",
  "Animal Lover",
  "Wildlife",

  // Home & Garden (25 interests)
  "Gardening",
  "Urban Gardening",
  "Container Gardening",
  "Hydroponic",
  "Composting",
  "Plants",
  "Succulents",
  "Houseplants",
  "Flowers",
  "Vegetable Gardening",
  "Herb Gardening",
  "Indoor Plants",
  "Cacti",
  "Bonsai",
  "Landscaping",
  "Yard Work",
  "DIY",
  "Home Projects",
  "Home Improvement",
  "Interior Design",
  "Home Decor",
  "Furniture Design",
  "Woodworking",
  "Upcycling",
  "Crafts",

  // Fashion & Style (25 interests)
  "Fashion",
  "Clothing",
  "Streetwear",
  "High Fashion",
  "Designer Fashion",
  "Vintage Fashion",
  "Thrifting",
  "Sustainable Fashion",
  "Minimalism",
  "Style",
  "Fashion Blogging",
  "Fashion Design",
  "Sewing",
  "Tailoring",
  "Makeup",
  "Makeup Artistry",
  "Beauty",
  "Skincare",
  "Cosmetics",
  "Hair Care",
  "Hairstyling",
  "Tattoos",
  "Piercing",
  "Jewelry",
  "Accessories",

  // Business & Entrepreneurship (25 interests)
  "Entrepreneurship",
  "Startups",
  "Side Hustles",
  "Business",
  "Freelancing",
  "Consulting",
  "Marketing",
  "Social Media Marketing",
  "Content Marketing",
  "SEO",
  "Digital Marketing",
  "Sales",
  "E-commerce",
  "Dropshipping",
  "Affiliate Marketing",
  "Investing",
  "Stock Market",
  "Real Estate",
  "Cryptocurrency",
  "Finance",
  "Personal Finance",
  "Budgeting",
  "Accounting",
  "Leadership",
  "Project Management",

  // Music & Entertainment (25 interests)
  "K-Pop",
  "K-Drama",
  "Pop Music",
  "Rock Music",
  "Hip Hop",
  "Rap",
  "R&B",
  "Soul Music",
  "Jazz",
  "Classical Music",
  "Orchestra",
  "Indie Music",
  "Electronic Music",
  "EDM",
  "House Music",
  "Techno",
  "Country Music",
  "Folk Music",
  "Reggae",
  "Latin Music",
  "Gospel",
  "Music Festivals",
  "Concerts",
  "Live Music",
  "Album Listening",

  // Lifestyle & Hobbies (20 interests)
  "Cosplay",
  "Conventions",
  "Comic Cons",
  "Fan Communities",
  "Anime Cons",
  "Trading Cards",
  "Collecting",
  "Model Building",
  "LEGO",
  "Puzzles",
  "Tabletop RPG",
  "Dungeons & Dragons",
  "D&D",
  "Wargaming",
  "Vintage Collecting",
  "Car Enthusiast",
  "Motorcycles",
  "Drones",
  "3D Printing",
  "Robotics",
];

export const INTEREST_CATEGORIES: Record<string, string[]> = {
  Technology: [
    "Coding",
    "Programming",
    "Web Development",
    "Mobile Development",
    "Frontend Development",
    "Backend Development",
    "Full Stack",
    "Software Engineering",
    "Data Science",
    "Machine Learning",
    "AI",
    "Artificial Intelligence",
    "Cybersecurity",
    "DevOps",
    "Cloud Computing",
    "Tech Startups",
    "App Development",
    "Game Development",
    "VR",
    "Augmented Reality",
    "Blockchain",
    "Open Source",
    "Tech",
    "Technology",
    "Hardware",
  ],
  Gaming: [
    "Gaming",
    "Video Games",
    "Board Games",
    "Esports",
    "Tabletop Gaming",
    "RPG",
    "Strategy Games",
    "Indie Games",
    "Console Gaming",
    "PC Gaming",
    "Mobile Games",
    "Competitive Gaming",
    "Streaming",
    "Gaming Communities",
    "Retro Gaming",
  ],
  Entertainment: [
    "Movies",
    "Film",
    "Cinematography",
    "TV Shows",
    "Netflix",
    "Animation",
    "Anime",
    "Manga",
    "Comics",
    "Graphic Novels",
    "Superhero",
    "Sci-Fi",
    "Fantasy",
    "Horror",
    "Comedy",
    "Drama",
    "Action Movies",
    "K-Drama",
  ],
  Creative: [
    "Art",
    "Drawing",
    "Painting",
    "Watercolor",
    "Sculpture",
    "Digital Art",
    "Graphic Design",
    "UI Design",
    "UX Design",
    "Web Design",
    "Photography",
    "Portrait Photography",
    "Landscape Photography",
    "Street Photography",
    "Videography",
    "Film Making",
    "Filmography",
    "Video Editing",
    "Music",
    "Singing",
    "Karaoke",
    "Instruments",
    "Piano",
    "Guitar",
    "Bass",
    "Drums",
    "Violin",
    "Music Production",
    "Producing",
    "DJing",
    "Beats",
    "Remix",
    "Writing",
    "Creative Writing",
    "Screenwriting",
    "Storytelling",
    "Blogging",
    "Vlogging",
    "Poetry",
    "Spoken Word",
    "Theater",
    "Acting",
    "Dance",
    "Improv",
    "Stand-up Comedy",
  ],
  Sports: [
    "Fitness",
    "Gym",
    "Strength Training",
    "Weightlifting",
    "CrossFit",
    "HIIT",
    "Running",
    "Marathon",
    "Jogging",
    "Track & Field",
    "Walking",
    "Hiking",
    "Trail Running",
    "Cycling",
    "Mountain Biking",
    "Road Biking",
    "Swimming",
    "Triathlon",
    "Basketball",
    "Soccer",
    "Football",
    "American Football",
    "Rugby",
    "Tennis",
    "Badminton",
    "Volleyball",
    "Beach Volleyball",
    "Baseball",
    "Softball",
    "Cricket",
    "Hockey",
    "Ice Hockey",
    "Field Hockey",
    "Lacrosse",
    "Martial Arts",
    "Karate",
    "Taekwondo",
    "Boxing",
    "Kickboxing",
    "Muay Thai",
    "MMA",
    "Wrestling",
    "Rock Climbing",
    "Bouldering",
    "Skateboarding",
    "Surfing",
    "Wakeboarding",
    "Snowboarding",
    "Skiing",
    "Ice Skating",
    "Team Sports",
  ],
  Wellness: [
    "Yoga",
    "Meditation",
    "Mindfulness",
    "Mental Health",
    "Therapy",
    "Counseling",
    "Pilates",
    "Stretching",
    "Contemporary Dance",
    "Ballet",
    "Hip Hop Dance",
    "Zumba",
    "Aerobics",
    "Wellness",
    "Spa",
    "Aromatherapy",
    "Nutrition",
    "Holistic Health",
    "Acupuncture",
    "Self-Care",
    "Personal Development",
    "Journaling",
    "Sleep Wellness",
    "Energy Work",
    "Chakra Balancing",
    "Breathwork",
    "Detox",
    "Gratitude",
  ],
  Outdoor: [
    "Backpacking",
    "Camping",
    "Glamping",
    "Outdoor Adventures",
    "Travel",
    "Road Trips",
    "Exploring",
    "Nature",
    "Parks",
    "National Parks",
    "Beaches",
    "Mountains",
    "Deserts",
    "Forests",
    "Islands",
    "Fishing",
    "Fly Fishing",
    "Hunting",
    "Kayaking",
    "Canoeing",
    "Paddleboarding",
    "Whitewater Rafting",
    "Adventure Sports",
    "Scuba Diving",
    "Snorkeling",
  ],
  Culinary: [
    "Cooking",
    "Baking",
    "Pastry",
    "Desserts",
    "Recipe Development",
    "Meal Prep",
    "Foodie",
    "Food Photography",
    "Restaurants",
    "Fine Dining",
    "Michelin Dining",
    "Home Cooking",
    "Home Baking",
    "BBQ",
    "Grilling",
    "Smoking Meats",
    "Sushi",
    "Asian Cuisine",
    "Italian Cooking",
    "Mexican Food",
    "Indian Cuisine",
    "Thai Food",
    "Mediterranean",
    "Vegan",
    "Vegetarian",
    "Gluten-Free",
    "Coffee",
    "Specialty Coffee",
    "Barista",
    "Tea",
    "Bubble Tea",
    "Wine",
    "Wine Tasting",
    "Beer",
    "Craft Beer",
    "Cocktails",
    "Mixology",
    "Brewing",
    "Fermentation",
  ],
  Intellectual: [
    "Reading",
    "Books",
    "Fiction",
    "Non-Fiction",
    "Mystery",
    "Thriller",
    "Romance",
    "Historical Fiction",
    "Self-Help",
    "Biography",
    "Memoirs",
    "Science",
    "Physics",
    "Chemistry",
    "Biology",
    "Astronomy",
    "Space",
    "Astrology",
    "History",
    "Ancient History",
    "Medieval History",
    "Philosophy",
    "Ethics",
    "Psychology",
    "Sociology",
    "Economics",
    "Politics",
    "Current Events",
    "News",
    "Languages",
    "Learning",
    "Education",
    "Podcasts",
    "TED Talks",
    "Documentaries",
  ],
  Social: [
    "Volunteering",
    "Charity",
    "Social Causes",
    "Community Service",
    "Activism",
    "Environmentalism",
    "Sustainability",
    "Climate Change",
    "Social Justice",
    "Mental Health Advocacy",
    "Networking",
    "Making Friends",
    "Leadership",
    "Public Speaking",
    "Mentoring",
    "Coaching",
    "Team Sports",
    "Group Activities",
    "Events",
    "Meetups",
    "Parties",
    "Nightlife",
    "Road Trips with Friends",
    "Group Hiking",
    "Study Groups",
    "Debate",
    "Philosophy Discussions",
    "Book Clubs",
    "Film Clubs",
    "Wine Tasting Groups",
    "Alumni Events",
    "Campus Clubs",
  ],
  Animals: [
    "Pets",
    "Dogs",
    "Dog Training",
    "Cats",
    "Cat Care",
    "Birds",
    "Exotic Pets",
    "Fish",
    "Aquariums",
    "Reptiles",
    "Snakes",
    "Animal Rescue",
    "Animal Welfare",
    "Animal Lover",
    "Wildlife",
  ],
  Home: [
    "Gardening",
    "Urban Gardening",
    "Container Gardening",
    "Hydroponic",
    "Composting",
    "Plants",
    "Succulents",
    "Houseplants",
    "Flowers",
    "Vegetable Gardening",
    "Herb Gardening",
    "Indoor Plants",
    "Cacti",
    "Bonsai",
    "Landscaping",
    "Yard Work",
    "DIY",
    "Home Projects",
    "Home Improvement",
    "Interior Design",
    "Home Decor",
    "Furniture Design",
    "Woodworking",
    "Upcycling",
    "Crafts",
  ],
  Fashion: [
    "Fashion",
    "Clothing",
    "Streetwear",
    "High Fashion",
    "Designer Fashion",
    "Vintage Fashion",
    "Thrifting",
    "Sustainable Fashion",
    "Minimalism",
    "Style",
    "Fashion Blogging",
    "Fashion Design",
    "Sewing",
    "Tailoring",
    "Makeup",
    "Makeup Artistry",
    "Beauty",
    "Skincare",
    "Cosmetics",
    "Hair Care",
    "Hairstyling",
    "Tattoos",
    "Piercing",
    "Jewelry",
    "Accessories",
  ],
  Business: [
    "Entrepreneurship",
    "Startups",
    "Side Hustles",
    "Business",
    "Freelancing",
    "Consulting",
    "Marketing",
    "Social Media Marketing",
    "Content Marketing",
    "SEO",
    "Digital Marketing",
    "Sales",
    "E-commerce",
    "Dropshipping",
    "Affiliate Marketing",
    "Investing",
    "Stock Market",
    "Real Estate",
    "Cryptocurrency",
    "Finance",
    "Personal Finance",
    "Budgeting",
    "Accounting",
    "Leadership",
    "Project Management",
  ],
  Music: [
    "K-Pop",
    "K-Drama",
    "Pop Music",
    "Rock Music",
    "Hip Hop",
    "Rap",
    "R&B",
    "Soul Music",
    "Jazz",
    "Classical Music",
    "Orchestra",
    "Indie Music",
    "Electronic Music",
    "EDM",
    "House Music",
    "Techno",
    "Country Music",
    "Folk Music",
    "Reggae",
    "Latin Music",
    "Gospel",
    "Music Festivals",
    "Concerts",
    "Live Music",
    "Album Listening",
  ],
  Lifestyle: [
    "Cosplay",
    "Conventions",
    "Comic Cons",
    "Fan Communities",
    "Anime Cons",
    "Trading Cards",
    "Collecting",
    "Model Building",
    "LEGO",
    "Puzzles",
    "Tabletop RPG",
    "Dungeons & Dragons",
    "D&D",
    "Wargaming",
    "Vintage Collecting",
    "Car Enthusiast",
    "Motorcycles",
    "Drones",
    "3D Printing",
    "Robotics",
  ],
};

/**
 * Get category for an interest (case-insensitive)
 * Used by discovery algorithm to compute category matches
 * Returns undefined if interest is not in any category (it's a niche interest)
 */
export const getInterestCategory = (interest: string): string | undefined => {
  const lowerInterest = interest.toLowerCase();
  for (const [category, interests] of Object.entries(INTEREST_CATEGORIES)) {
    if (interests.some((i) => i.toLowerCase() === lowerInterest)) {
      return category;
    }
  }
  return undefined;
};
