/**
 * Comprehensive list of college majors.
 * Alphabetically sorted across common fields of study.
 */

export const MAJORS = [
  "Aerospace Engineering",
  "Agricultural Engineering",
  "Biomedical Engineering",
  "Chemical Engineering",
  "Civil Engineering",
  "Computer Engineering",
  "Electrical Engineering",
  "Engineering Physics",
  "Environmental Engineering",
  "Geological Engineering",
  "Geotechnical Engineering",
  "Industrial Engineering",
  "Materials Engineering",
  "Mechanical Engineering",
  "Mining Engineering",
  "Naval Engineering",
  "Nuclear Engineering",
  "Petroleum Engineering",
  "Software Engineering",
  "Structural Engineering",
  "Systems Engineering",
  "Textile Engineering",
  "Transportation Engineering",
  "Water Resources Engineering",
  "Bioengineering",
  "Nanoengineering",
  "Robotics Engineering",
  "Renewable Energy Engineering",
  "Manufacturing Engineering",
  "Thermal Engineering",
  "Astronomy",
  "Astrophysics",
  "Chemistry",
  "Environmental Science",
  "Geology",
  "Geophysics",
  "Meteorology",
  "Oceanography",
  "Physics",
  "Planetary Science",
  "Atmospheric Science",
  "Earth Sciences",
  "Geochemistry",
  "Paleontology",
  "Crystallography",
  "Spectroscopy",
  "Materials Science",
  "Nanotechnology",
  "Applied Physics",
  "Environmental Geology",
  "Marine Science",
  "Soil Science",
  "Mineralogy",
  "Petrology",
  "Hydrology",
  "Animal Science",
  "Anthropology",
  "Applied Mathematics",
  "Archaeology",
  "Behavioral Science",
  "Biochemistry",
  "Biological Engineering",
  "Biology",
  "Biophysics",
  "Biotechnology",
  "Botany",
  "Cellular Biology",
  "Conservation Biology",
  "Developmental Biology",
  "Ecology",
  "Evolutionary Biology",
  "Genetics",
  "Immunology",
  "Marine Biology",
  "Microbiology",
  "Molecular Biology",
  "Neurobiology",
  "Neuroscience",
  "Physiology",
  "Plant Sciences",
  "Zoology",
  "Entomology",
  "Ornithology",
  "Artificial Intelligence",
  "Big Data",
  "Bioinformatics",
  "Computer Science",
  "Computer Systems",
  "Cybersecurity",
  "Data Science",
  "Database Management",
  "Information Science",
  "Information Systems",
  "Information Technology",
  "Machine Learning",
  "Network Administration",
  "Software Development",
  "Web Development",
  "Cloud Computing",
  "Game Development",
  "Human-Computer Interaction",
  "Actuarial Science",
  "Computational Mathematics",
  "Discrete Mathematics",
  "Financial Mathematics",
  "Mathematics",
  "Mathematical Physics",
  "Pure Mathematics",
  "Statistics",
  "Mathematical Statistics",
  "Biomathematics",
  "Cryptography",
  "Anesthesiology",
  "Athletic Training",
  "Audiology",
  "Cardiothoracic Surgery",
  "Clinical Laboratory Science",
  "Clinical Psychology",
  "Dentistry",
  "Dermatology",
  "Dietetics",
  "Emergency Medicine",
  "Family Medicine",
  "Forensic Science",
  "General Surgery",
  "Gerontology",
  "Health Administration",
  "Health Information Management",
  "Healthcare Management",
  "Internal Medicine",
  "Medical Laboratory Science",
  "Medicine",
  "Mental Health Counseling",
  "Naturopathic Medicine",
  "Neurosurgery",
  "Nursing",
  "Occupational Therapy",
  "Oncology",
  "Ophthalmology",
  "Optometry",
  "Orthopedic Surgery",
  "Otolaryngology",
  "Pathology",
  "Pediatrics",
  "Pharmacy",
  "Physical Therapy",
  "Physician Assistant",
  "Podiatry",
  "Psychiatry",
  "Public Health",
  "Radiation Therapy",
  "Radiology",
  "Respiratory Therapy",
  "Surgery",
  "Veterinary Medicine",
  "Accounting",
  "Advertising",
  "Business Administration",
  "Business Analytics",
  "Business Economics",
  "Business Management",
  "Entrepreneurship",
  "Facility Management",
  "Finance",
  "Financial Analysis",
  "Financial Planning",
  "Hospitality Management",
  "Human Resources",
  "International Business",
  "Investment Management",
  "Labor Relations",
  "Management",
  "Management Information Systems",
  "Marketing",
  "Nonprofit Management",
  "Operations Management",
  "Organizational Management",
  "Project Management",
  "Public Administration",
  "Real Estate",
  "Retail Management",
  "Supply Chain Management",
  "Applied Behavioral Analysis",
  "Criminology",
  "Criminal Justice",
  "Economics",
  "Education",
  "Elementary Education",
  "Family and Consumer Sciences",
  "Global Studies",
  "Government",
  "History",
  "Human Development",
  "International Affairs",
  "International Relations",
  "Journalism",
  "Law",
  "Legal Studies",
  "Liberal Arts",
  "Middle School Education",
  "Peace and Conflict Studies",
  "Political Science",
  "Psychology",
  "Public Policy",
  "Secondary Education",
  "Social Science",
  "Social Work",
  "Sociology",
  "Special Education",
  "Urban Studies",
  "Womens Studies",
  "American Studies",
  "Ancient Languages",
  "Classics",
  "Communication",
  "Comparative Literature",
  "Creative Writing",
  "Cultural Studies",
  "English",
  "English Literature",
  "Environmental Studies",
  "Ethics",
  "European Studies",
  "Film Studies",
  "Foreign Languages",
  "French",
  "German",
  "History of Art",
  "Humanities",
  "Italian",
  "Japanese",
  "Latin American Studies",
  "Literature",
  "Medieval Studies",
  "Middle Eastern Studies",
  "Modern Languages",
  "Comparative Religion",
  "Eastern Philosophy",
  "Islamic Studies",
  "Jewish Studies",
  "Metaphysics",
  "Philosophy",
  "Philosophy of Science",
  "Religious Studies",
  "Theology",
  "Western Philosophy",
  "Logic",
  "Phenomenology",
  "Philosophy of Mind",
  "Aesthetics",
  "Animation",
  "Applied Art",
  "Architecture",
  "Art",
  "Art Education",
  "Art History",
  "Ceramic Art",
  "Commercial Art",
  "Costume Design",
  "Dance",
  "Digital Art",
  "Drama",
  "Fashion Design",
  "Fiber Arts",
  "Fine Arts",
  "Graphic Design",
  "Illustration",
  "Industrial Design",
  "Interior Design",
  "Jewelry Design",
  "Landscape Architecture",
  "Metal Arts",
  "Music",
  "Music Composition",
  "Music Production",
  "Photography",
  "Printmaking",
  "Theater",
  "Band",
  "Choral Music",
  "Composition",
  "Jazz Studies",
  "Music Education",
  "Music Performance",
  "Music Theory",
  "Opera",
  "Theater Performance",
  "Afrikaans",
  "Aramaic",
  "Arabic",
  "Chinese",
  "Comparative Linguistics",
  "Czech",
  "Dutch",
  "English Language",
  "Finnish",
  "French Language",
  "German Language",
  "Greek",
  "Hebrew",
  "Hindi",
  "Japanese Language",
  "Korean",
  "Latin",
  "Linguistics",
  "Russian",
  "Spanish Language",
  "Broadcasting",
  "Communication Studies",
  "Communications",
  "Digital Media",
  "Media Arts",
  "Media Production",
  "Media Studies",
  "Multimedia",
  "Public Relations",
  "Radio/Television",
  "Social Media Marketing",
  "Technical Communications",
  "Video Production",
  "Agricultural Education",
  "Business Education",
  "Educational Leadership",
  "Higher Education",
  "Physical Education",
  "Teaching",
  "Exercise Science",
  "Health and Physical Education",
  "Kinesiology",
  "Physical Fitness",
  "Sports Administration",
  "Sports Coaching",
  "Sports Management",
  "Sports Medicine",
  "Sports Psychology",
  "Sports Science",
  "Strength and Conditioning",
  "Ecosystem Management",
  "Environmental Biology",
  "Environmental Conservation",
  "Environmental Design",
  "Environmental Management",
  "Environmental Policy",
  "Forestry",
  "Parks and Recreation",
  "Wildlife Management",
  "Agribusiness",
  "Agricultural Business",
  "Agricultural Communications",
  "Agricultural Economics",
  "Agricultural Science",
  "Crop Science",
  "Environmental Horticulture",
  "Horticulture",
  "Plant Science",
  "Sustainable Agriculture",
  "Viticulture",
  "Air Force ROTC",
  "Army ROTC",
  "Coast Guard ROTC",
  "Military History",
  "Military Science",
  "Naval Science",
  "Marine Corps ROTC",
  "Strategic Studies",
  "Undecided",
  "General Studies",
  "Interdisciplinary Studies",
  "Exploratory Studies",
  "Self-Designed Major",
] as const;

export type Major = (typeof MAJORS)[number];
