import { PrismaClient } from "@/generated/prisma";
import * as bcrypt from "bcrypt";
import * as fs from "fs";
import * as path from "path";
import { supabaseAdmin } from "@/lib/supabaseAdmin";

/*
login:
testuser{i}@njit.edu or testuser{i}@northeastern.edu
password123
*/
const prisma = new PrismaClient();

const njitUsersData = [
  {
    email: "testuser1@njit.edu",
    name: "Alice Smith",
    birthdate: "2002-04-12",
    gender: "Female",
    pronouns: "she/her",
    bio: "Passionate about coding and fitness. Loves to explore new technologies.",
    university_year: 3,
    major: "Computer Science",
    grad_year: 2025,
    interests: ["Coding", "Fitness", "Reading"],
    intent: "Dating",
    gender_preference: ["Male"],
    sexual_orientation: "Heterosexual",
    min_age: 20,
    max_age: 24,
    avatarFile: "p1.jpeg",
  },
  {
    email: "testuser2@njit.edu",
    name: "Fiona Miller",
    birthdate: "2003-09-08",
    gender: "Female",
    pronouns: "she/her",
    bio: "Loves hiking and photography. Always up for a new adventure.",
    university_year: 2,
    major: "Design",
    grad_year: 2026,
    interests: ["Photography", "Travel", "Fitness"],
    intent: "Friendship",
    gender_preference: ["All"],
    sexual_orientation: "Bisexual",
    min_age: 19,
    max_age: 23,
    avatarFile: "p2.jpeg",
  },
  {
    email: "testuser3@njit.edu",
    name: "Michael Brown",
    birthdate: "2001-11-15",
    gender: "Male",
    pronouns: "he/him",
    bio: "Enjoys reading and photography. A creative soul.",
    university_year: 4,
    major: "Mechanical Engineering",
    grad_year: 2024,
    interests: ["Reading", "Photography", "Gaming"],
    intent: "Dating",
    gender_preference: ["Female"],
    sexual_orientation: "Bisexual",
    min_age: 21,
    max_age: 26,
    avatarFile: "p3.jpeg",
  },
  {
    email: "testuser4@njit.edu",
    name: "Diana Prince",
    birthdate: "2004-03-02",
    gender: "Female",
    pronouns: "she/her",
    bio: "Fitness enthusiast and music lover. Always ready for an adventure.",
    university_year: 1,
    major: "Civil Engineering",
    grad_year: 2027,
    interests: ["Fitness", "Music", "Photography"],
    intent: "Dating",
    gender_preference: ["All"],
    sexual_orientation: "Heterosexual",
    min_age: 18,
    max_age: 22,
    avatarFile: "p4.jpeg",
  },
  {
    email: "testuser5@njit.edu",
    name: "Eve Adams",
    birthdate: "2002-07-04",
    gender: "Female",
    pronouns: "she/her",
    bio: "Loves to code and play games. Always learning something new.",
    university_year: 3,
    major: "Business",
    grad_year: 2025,
    interests: ["Coding", "Gaming", "Fitness"],
    intent: "Friendship",
    gender_preference: ["Male", "Female"],
    sexual_orientation: "Lesbian",
    min_age: 20,
    max_age: 24,
    avatarFile: "p5.jpeg",
  },
  {
    email: "testuser6@njit.edu",
    name: "Frank White",
    birthdate: "2001-05-21",
    gender: "Male",
    pronouns: "he/him",
    bio: "Photography hobbyist with a passion for music. Exploring creativity.",
    university_year: 4,
    major: "Architecture",
    grad_year: 2024,
    interests: ["Photography", "Music", "Reading"],
    intent: "Dating",
    gender_preference: ["Female"],
    sexual_orientation: "Heterosexual",
    min_age: 21,
    max_age: 26,
    avatarFile: "p6.jpeg",
  },
  {
    email: "testuser7@njit.edu",
    name: "Grace Lee",
    birthdate: "2003-08-30",
    gender: "Female",
    pronouns: "she/her",
    bio: "Enjoys reading and staying fit. A quiet but adventurous spirit.",
    university_year: 2,
    major: "Computer Science",
    grad_year: 2026,
    interests: ["Reading", "Fitness", "Coding"],
    intent: "Friendship",
    gender_preference: ["Male"],
    sexual_orientation: "Heterosexual",
    min_age: 19,
    max_age: 23,
    avatarFile: "p7.jpeg",
  },
  {
    email: "testuser8@njit.edu",
    name: "Henry Green",
    birthdate: "2004-02-12",
    gender: "Male",
    pronouns: "he/him",
    bio: "Gamer and tech enthusiast. Always up for a good conversation.",
    university_year: 1,
    major: "Information Technology",
    grad_year: 2027,
    interests: ["Gaming", "Coding", "Music"],
    intent: "Dating",
    gender_preference: ["All"],
    sexual_orientation: "Gay",
    min_age: 18,
    max_age: 22,
    avatarFile: "p8.jpeg",
  },
  {
    email: "testuser9@njit.edu",
    name: "Ivy Chen",
    birthdate: "2002-12-12",
    gender: "Female",
    pronouns: "she/her",
    bio: "Music composer and artist. Expressing through sounds and visuals.",
    university_year: 3,
    major: "Mechanical Engineering",
    grad_year: 2025,
    interests: ["Music", "Photography", "Reading"],
    intent: "Friendship",
    gender_preference: ["Male"],
    sexual_orientation: "Heterosexual",
    min_age: 20,
    max_age: 24,
    avatarFile: "p9.jpeg",
  },
  {
    email: "testuser10@njit.edu",
    name: "Jack Taylor",
    birthdate: "2000-06-30",
    gender: "Male",
    pronouns: "he/him",
    bio: "Fitness trainer and outdoor adventurer. Loves challenges.",
    university_year: 4,
    major: "Civil Engineering",
    grad_year: 2024,
    interests: ["Fitness", "Gaming", "Music"],
    intent: "Dating",
    gender_preference: ["Female"],
    sexual_orientation: "Heterosexual",
    min_age: 21,
    max_age: 26,
    avatarFile: "p10.jpeg",
  },
  // Edge cases and additional diversity
  {
    email: "testuser11@njit.edu",
    name: "Sarah Johnson",
    birthdate: "2003-01-15",
    gender: "Female",
    pronouns: "she/her",
    bio: "No interests listed - testing edge case.",
    university_year: 2,
    major: "Computer Science",
    grad_year: 2026,
    interests: [],
    intent: "Friendship",
    gender_preference: ["All"],
    sexual_orientation: "Heterosexual",
    min_age: 19,
    max_age: 23,
    avatarFile: "p1.jpeg",
  },
  {
    email: "testuser12@njit.edu",
    name: "James Wilson",
    birthdate: "2001-06-20",
    gender: "Male",
    pronouns: "he/him",
    bio: "Serious about finding a long-term partner.",
    university_year: 3,
    major: "Computer Science",
    grad_year: 2025,
    interests: ["Coding", "Reading", "Travel"],
    intent: "Serious Relationship",
    gender_preference: ["Female"],
    sexual_orientation: "Heterosexual",
    min_age: 20,
    max_age: 25,
    avatarFile: "p3.jpeg",
  },
  {
    email: "testuser13@njit.edu",
    name: "Lisa Chen",
    birthdate: "2002-11-10",
    gender: "Female",
    pronouns: "she/her",
    bio: "Just here for casual fun, nothing serious.",
    university_year: 3,
    major: "Business",
    grad_year: 2025,
    interests: ["Gaming", "Music", "Fitness"],
    intent: "Casual Dating",
    gender_preference: ["Male"],
    sexual_orientation: "Heterosexual",
    min_age: 21,
    max_age: 25,
    avatarFile: "p2.jpeg",
  },
  {
    email: "testuser14@njit.edu",
    name: "Marcus Rodriguez",
    birthdate: "2002-03-25",
    gender: "Male",
    pronouns: "he/him",
    bio: "Looking for study buddies and academic friends.",
    university_year: 2,
    major: "Computer Science",
    grad_year: 2026,
    interests: ["Coding", "Reading"],
    intent: "Study Buddy",
    gender_preference: ["All"],
    sexual_orientation: "Gay",
    min_age: 19,
    max_age: 24,
    avatarFile: "p8.jpeg",
  },
  {
    email: "testuser15@njit.edu",
    name: "Emma Davis",
    birthdate: "2001-09-30",
    gender: "Female",
    pronouns: "she/her",
    bio: "Open to anything, just seeing what's out there.",
    university_year: 4,
    major: "Civil Engineering",
    grad_year: 2024,
    interests: ["Fitness", "Photography", "Travel"],
    intent: "Unsure",
    gender_preference: ["All"],
    sexual_orientation: "Bisexual",
    min_age: 20,
    max_age: 26,
    avatarFile: "p4.jpeg",
  },
  {
    email: "testuser16@njit.edu",
    name: "Noah Bennett",
    birthdate: "2003-07-12",
    gender: "Male",
    pronouns: "he/him",
    bio: "Into fitness and outdoor activities.",
    university_year: 1,
    major: "Civil Engineering",
    grad_year: 2027,
    interests: ["Fitness", "Travel", "Gaming"],
    intent: "Dating",
    gender_preference: ["Female"],
    sexual_orientation: "Heterosexual",
    min_age: 18,
    max_age: 22,
    avatarFile: "p10.jpeg",
  },
  {
    email: "testuser17@njit.edu",
    name: "Rachel Green",
    birthdate: "2000-02-14",
    gender: "Female",
    pronouns: "she/her",
    bio: "Older student, back in school after time off.",
    university_year: 2,
    major: "Business",
    grad_year: 2026,
    interests: ["Reading", "Travel", "Music"],
    intent: "Dating",
    gender_preference: ["Male"],
    sexual_orientation: "Heterosexual",
    min_age: 23,
    max_age: 35,
    avatarFile: "p5.jpeg",
  },
  {
    email: "testuser18@njit.edu",
    name: "David Kim",
    birthdate: "2004-05-08",
    gender: "Male",
    pronouns: "he/him",
    bio: "Younger student, interested in tech and music.",
    university_year: 1,
    major: "Information Technology",
    grad_year: 2027,
    interests: ["Coding", "Music", "Gaming"],
    intent: "Casual Dating",
    gender_preference: ["All"],
    sexual_orientation: "Gay",
    min_age: 18,
    max_age: 21,
    avatarFile: "p8.jpeg",
  },
  {
    email: "testuser19@njit.edu",
    name: "Jessica Martinez",
    birthdate: "2002-10-22",
    gender: "Female",
    pronouns: "she/her",
    bio: "Architecture student with creative interests.",
    university_year: 3,
    major: "Architecture",
    grad_year: 2025,
    interests: ["Photography", "Travel", "Music"],
    intent: "Friendship",
    gender_preference: ["All"],
    sexual_orientation: "Bisexual",
    min_age: 20,
    max_age: 24,
    avatarFile: "p2.jpeg",
  },
  {
    email: "testuser20@njit.edu",
    name: "Kevin Thompson",
    birthdate: "2001-12-03",
    gender: "Male",
    pronouns: "he/him",
    bio: "Mechanical engineer with diverse interests.",
    university_year: 4,
    major: "Mechanical Engineering",
    grad_year: 2024,
    interests: ["Reading", "Gaming", "Travel"],
    intent: "Dating",
    gender_preference: ["Female"],
    sexual_orientation: "Heterosexual",
    min_age: 21,
    max_age: 26,
    avatarFile: "p3.jpeg",
  },
  {
    email: "testuser21@njit.edu",
    name: "Sophia Anderson",
    birthdate: "2003-04-17",
    gender: "Female",
    pronouns: "she/her",
    bio: "Design student with passion for visual arts.",
    university_year: 2,
    major: "Design",
    grad_year: 2026,
    interests: ["Photography", "Music", "Reading"],
    intent: "Friendship",
    gender_preference: ["All"],
    sexual_orientation: "Lesbian",
    min_age: 19,
    max_age: 23,
    avatarFile: "p7.jpeg",
  },
  {
    email: "testuser22@njit.edu",
    name: "Tyler Johnson",
    birthdate: "2002-08-28",
    gender: "Male",
    pronouns: "he/him",
    bio: "Business student looking to network and date.",
    university_year: 3,
    major: "Business",
    grad_year: 2025,
    interests: ["Coding", "Music", "Fitness"],
    intent: "Casual Dating",
    gender_preference: ["Female"],
    sexual_orientation: "Heterosexual",
    min_age: 20,
    max_age: 24,
    avatarFile: "p6.jpeg",
  },
  {
    email: "testuser23@njit.edu",
    name: "Olivia Taylor",
    birthdate: "2001-01-11",
    gender: "Female",
    pronouns: "she/her",
    bio: "CS major seeking serious relationship.",
    university_year: 4,
    major: "Computer Science",
    grad_year: 2024,
    interests: ["Coding", "Reading", "Fitness"],
    intent: "Serious Relationship",
    gender_preference: ["Male"],
    sexual_orientation: "Heterosexual",
    min_age: 22,
    max_age: 27,
    avatarFile: "p1.jpeg",
  },
  {
    email: "testuser24@njit.edu",
    name: "Christopher Lee",
    birthdate: "2003-11-05",
    gender: "Male",
    pronouns: "he/him",
    bio: "Freshman into gaming and tech.",
    university_year: 1,
    major: "Information Technology",
    grad_year: 2027,
    interests: ["Gaming", "Coding"],
    intent: "Friendship",
    gender_preference: ["All"],
    sexual_orientation: "Gay",
    min_age: 18,
    max_age: 21,
    avatarFile: "p9.jpeg",
  },
  {
    email: "testuser25@njit.edu",
    name: "Amanda White",
    birthdate: "2002-06-19",
    gender: "Female",
    pronouns: "she/her",
    bio: "Mechanical engineering student with broad interests.",
    university_year: 3,
    major: "Mechanical Engineering",
    grad_year: 2025,
    interests: ["Fitness", "Photography", "Travel"],
    intent: "Dating",
    gender_preference: ["Male", "Female"],
    sexual_orientation: "Bisexual",
    min_age: 20,
    max_age: 24,
    avatarFile: "p4.jpeg",
  },
  {
    email: "testuser26@njit.edu",
    name: "Brandon Harris",
    birthdate: "2001-03-09",
    gender: "Male",
    pronouns: "he/him",
    bio: "Architecture student with creative flair.",
    university_year: 4,
    major: "Architecture",
    grad_year: 2024,
    interests: ["Photography", "Music", "Travel"],
    intent: "Casual Dating",
    gender_preference: ["All"],
    sexual_orientation: "Bisexual",
    min_age: 21,
    max_age: 26,
    avatarFile: "p10.jpeg",
  },
  {
    email: "testuser27@njit.edu",
    name: "Victoria Moore",
    birthdate: "2003-09-13",
    gender: "Female",
    pronouns: "she/her",
    bio: "Business major into fitness and music.",
    university_year: 2,
    major: "Business",
    grad_year: 2026,
    interests: ["Fitness", "Music", "Travel"],
    intent: "Dating",
    gender_preference: ["Male"],
    sexual_orientation: "Heterosexual",
    min_age: 19,
    max_age: 23,
    avatarFile: "p2.jpeg",
  },
  {
    email: "testuser28@njit.edu",
    name: "Andrew Jackson",
    birthdate: "2002-07-21",
    gender: "Male",
    pronouns: "he/him",
    bio: "Civil engineer seeking study buddy or more.",
    university_year: 3,
    major: "Civil Engineering",
    grad_year: 2025,
    interests: ["Coding", "Reading", "Gaming"],
    intent: "Study Buddy",
    gender_preference: ["All"],
    sexual_orientation: "Gay",
    min_age: 20,
    max_age: 24,
    avatarFile: "p8.jpeg",
  },
  {
    email: "testuser29@njit.edu",
    name: "Nicole Scott",
    birthdate: "2001-10-06",
    gender: "Female",
    pronouns: "she/her",
    bio: "Design student with artistic spirit.",
    university_year: 4,
    major: "Design",
    grad_year: 2024,
    interests: ["Photography", "Music", "Travel"],
    intent: "Friendship",
    gender_preference: ["All"],
    sexual_orientation: "Pansexual",
    min_age: 21,
    max_age: 26,
    avatarFile: "p5.jpeg",
  },
  {
    email: "testuser30@njit.edu",
    name: "Matthew Edwards",
    birthdate: "2004-02-28",
    gender: "Male",
    pronouns: "he/him",
    bio: "IT student passionate about technology.",
    university_year: 1,
    major: "Information Technology",
    grad_year: 2027,
    interests: ["Coding", "Gaming", "Music"],
    intent: "Casual Dating",
    gender_preference: ["All"],
    sexual_orientation: "Gay",
    min_age: 18,
    max_age: 21,
    avatarFile: "p9.jpeg",
  },
];

const northeasternUsersData = [
  {
    email: "testuser1@northeastern.edu",
    name: "Alice Smith",
    birthdate: "2002-04-12",
    gender: "Female",
    pronouns: "she/her",
    bio: "Passionate about coding and fitness. Loves to explore new technologies.",
    university_year: 3,
    major: "Computer Science",
    grad_year: 2025,
    interests: ["Coding", "Fitness", "Reading"],
    intent: "Dating",
    gender_preference: ["Male"],
    sexual_orientation: "Heterosexual",
    min_age: 20,
    max_age: 24,
    avatarFile: "p1.jpeg",
  },
  {
    email: "testuser2@northeastern.edu",
    name: "Fiona Miller",
    birthdate: "2003-09-08",
    gender: "Female",
    pronouns: "she/her",
    bio: "Loves hiking and photography. Always up for a new adventure.",
    university_year: 2,
    major: "Design",
    grad_year: 2026,
    interests: ["Photography", "Travel", "Fitness"],
    intent: "Friendship",
    gender_preference: ["All"],
    sexual_orientation: "Bisexual",
    min_age: 19,
    max_age: 23,
    avatarFile: "p2.jpeg",
  },
  {
    email: "testuser3@northeastern.edu",
    name: "Michael Brown",
    birthdate: "2001-11-15",
    gender: "Male",
    pronouns: "he/him",
    bio: "Enjoys reading and photography. A creative soul.",
    university_year: 4,
    major: "Mechanical Engineering",
    grad_year: 2024,
    interests: ["Reading", "Photography", "Gaming"],
    intent: "Dating",
    gender_preference: ["Female"],
    sexual_orientation: "Bisexual",
    min_age: 21,
    max_age: 26,
    avatarFile: "p3.jpeg",
  },
  {
    email: "testuser4@northeastern.edu",
    name: "Diana Prince",
    birthdate: "2004-03-02",
    gender: "Female",
    pronouns: "she/her",
    bio: "Fitness enthusiast and music lover. Always ready for an adventure.",
    university_year: 1,
    major: "Civil Engineering",
    grad_year: 2027,
    interests: ["Fitness", "Music", "Photography"],
    intent: "Dating",
    gender_preference: ["All"],
    sexual_orientation: "Heterosexual",
    min_age: 18,
    max_age: 22,
    avatarFile: "p4.jpeg",
  },
  {
    email: "testuser5@northeastern.edu",
    name: "Eve Adams",
    birthdate: "2002-07-04",
    gender: "Female",
    pronouns: "she/her",
    bio: "Loves to code and play games. Always learning something new.",
    university_year: 3,
    major: "Business",
    grad_year: 2025,
    interests: ["Coding", "Gaming", "Fitness"],
    intent: "Friendship",
    gender_preference: ["Male", "Female"],
    sexual_orientation: "Lesbian",
    min_age: 20,
    max_age: 24,
    avatarFile: "p5.jpeg",
  },
  {
    email: "testuser6@northeastern.edu",
    name: "Frank White",
    birthdate: "2001-05-21",
    gender: "Male",
    pronouns: "he/him",
    bio: "Photography hobbyist with a passion for music. Exploring creativity.",
    university_year: 4,
    major: "Architecture",
    grad_year: 2024,
    interests: ["Photography", "Music", "Reading"],
    intent: "Dating",
    gender_preference: ["Female"],
    sexual_orientation: "Heterosexual",
    min_age: 21,
    max_age: 26,
    avatarFile: "p6.jpeg",
  },
  {
    email: "testuser7@northeastern.edu",
    name: "Grace Lee",
    birthdate: "2003-08-30",
    gender: "Female",
    pronouns: "she/her",
    bio: "Enjoys reading and staying fit. A quiet but adventurous spirit.",
    university_year: 2,
    major: "Computer Science",
    grad_year: 2026,
    interests: ["Reading", "Fitness", "Coding"],
    intent: "Friendship",
    gender_preference: ["Male"],
    sexual_orientation: "Heterosexual",
    min_age: 19,
    max_age: 23,
    avatarFile: "p7.jpeg",
  },
  {
    email: "testuser8@northeastern.edu",
    name: "Henry Green",
    birthdate: "2004-02-12",
    gender: "Male",
    pronouns: "he/him",
    bio: "Gamer and tech enthusiast. Always up for a good conversation.",
    university_year: 1,
    major: "Information Technology",
    grad_year: 2027,
    interests: ["Gaming", "Coding", "Music"],
    intent: "Dating",
    gender_preference: ["All"],
    sexual_orientation: "Gay",
    min_age: 18,
    max_age: 22,
    avatarFile: "p8.jpeg",
  },
  {
    email: "testuser9@northeastern.edu",
    name: "Ivy Chen",
    birthdate: "2002-12-12",
    gender: "Female",
    pronouns: "she/her",
    bio: "Music composer and artist. Expressing through sounds and visuals.",
    university_year: 3,
    major: "Mechanical Engineering",
    grad_year: 2025,
    interests: ["Music", "Photography", "Reading"],
    intent: "Friendship",
    gender_preference: ["Male"],
    sexual_orientation: "Heterosexual",
    min_age: 20,
    max_age: 24,
    avatarFile: "p9.jpeg",
  },
  {
    email: "testuser10@northeastern.edu",
    name: "Jack Taylor",
    birthdate: "2000-06-30",
    gender: "Male",
    pronouns: "he/him",
    bio: "Fitness trainer and outdoor adventurer. Loves challenges.",
    university_year: 4,
    major: "Civil Engineering",
    grad_year: 2024,
    interests: ["Fitness", "Gaming", "Music"],
    intent: "Dating",
    gender_preference: ["Female"],
    sexual_orientation: "Heterosexual",
    min_age: 21,
    max_age: 26,
    avatarFile: "p10.jpeg",
  },
  // Edge cases and additional diversity
  {
    email: "testuser11@northeastern.edu",
    name: "Sarah Johnson",
    birthdate: "2003-01-15",
    gender: "Female",
    pronouns: "she/her",
    bio: "No interests listed - testing edge case.",
    university_year: 2,
    major: "Computer Science",
    grad_year: 2026,
    interests: [],
    intent: "Friendship",
    gender_preference: ["All"],
    sexual_orientation: "Heterosexual",
    min_age: 19,
    max_age: 23,
    avatarFile: "p1.jpeg",
  },
  {
    email: "testuser12@northeastern.edu",
    name: "James Wilson",
    birthdate: "2001-06-20",
    gender: "Male",
    pronouns: "he/him",
    bio: "Serious about finding a long-term partner.",
    university_year: 3,
    major: "Computer Science",
    grad_year: 2025,
    interests: ["Coding", "Reading", "Travel"],
    intent: "Serious Relationship",
    gender_preference: ["Female"],
    sexual_orientation: "Heterosexual",
    min_age: 20,
    max_age: 25,
    avatarFile: "p3.jpeg",
  },
  {
    email: "testuser13@northeastern.edu",
    name: "Lisa Chen",
    birthdate: "2002-11-10",
    gender: "Female",
    pronouns: "she/her",
    bio: "Just here for casual fun, nothing serious.",
    university_year: 3,
    major: "Business",
    grad_year: 2025,
    interests: ["Gaming", "Music", "Fitness"],
    intent: "Casual Dating",
    gender_preference: ["Male"],
    sexual_orientation: "Heterosexual",
    min_age: 21,
    max_age: 25,
    avatarFile: "p2.jpeg",
  },
  {
    email: "testuser14@northeastern.edu",
    name: "Marcus Rodriguez",
    birthdate: "2002-03-25",
    gender: "Male",
    pronouns: "he/him",
    bio: "Looking for study buddies and academic friends.",
    university_year: 2,
    major: "Computer Science",
    grad_year: 2026,
    interests: ["Coding", "Reading"],
    intent: "Study Buddy",
    gender_preference: ["All"],
    sexual_orientation: "Gay",
    min_age: 19,
    max_age: 24,
    avatarFile: "p8.jpeg",
  },
  {
    email: "testuser15@northeastern.edu",
    name: "Emma Davis",
    birthdate: "2001-09-30",
    gender: "Female",
    pronouns: "she/her",
    bio: "Open to anything, just seeing what's out there.",
    university_year: 4,
    major: "Civil Engineering",
    grad_year: 2024,
    interests: ["Fitness", "Photography", "Travel"],
    intent: "Unsure",
    gender_preference: ["All"],
    sexual_orientation: "Bisexual",
    min_age: 20,
    max_age: 26,
    avatarFile: "p4.jpeg",
  },
  {
    email: "testuser16@northeastern.edu",
    name: "Noah Bennett",
    birthdate: "2003-07-12",
    gender: "Male",
    pronouns: "he/him",
    bio: "Into fitness and outdoor activities.",
    university_year: 1,
    major: "Civil Engineering",
    grad_year: 2027,
    interests: ["Fitness", "Travel", "Gaming"],
    intent: "Dating",
    gender_preference: ["Female"],
    sexual_orientation: "Heterosexual",
    min_age: 18,
    max_age: 22,
    avatarFile: "p10.jpeg",
  },
  {
    email: "testuser17@northeastern.edu",
    name: "Rachel Green",
    birthdate: "2000-02-14",
    gender: "Female",
    pronouns: "she/her",
    bio: "Older student, back in school after time off.",
    university_year: 2,
    major: "Business",
    grad_year: 2026,
    interests: ["Reading", "Travel", "Music"],
    intent: "Dating",
    gender_preference: ["Male"],
    sexual_orientation: "Heterosexual",
    min_age: 23,
    max_age: 35,
    avatarFile: "p5.jpeg",
  },
  {
    email: "testuser18@northeastern.edu",
    name: "David Kim",
    birthdate: "2004-05-08",
    gender: "Male",
    pronouns: "he/him",
    bio: "Younger student, interested in tech and music.",
    university_year: 1,
    major: "Information Technology",
    grad_year: 2027,
    interests: ["Coding", "Music", "Gaming"],
    intent: "Casual Dating",
    gender_preference: ["All"],
    sexual_orientation: "Gay",
    min_age: 18,
    max_age: 21,
    avatarFile: "p8.jpeg",
  },
  {
    email: "testuser19@northeastern.edu",
    name: "Jessica Martinez",
    birthdate: "2002-10-22",
    gender: "Female",
    pronouns: "she/her",
    bio: "Architecture student with creative interests.",
    university_year: 3,
    major: "Architecture",
    grad_year: 2025,
    interests: ["Photography", "Travel", "Music"],
    intent: "Friendship",
    gender_preference: ["All"],
    sexual_orientation: "Bisexual",
    min_age: 20,
    max_age: 24,
    avatarFile: "p2.jpeg",
  },
  {
    email: "testuser20@northeastern.edu",
    name: "Kevin Thompson",
    birthdate: "2001-12-03",
    gender: "Male",
    pronouns: "he/him",
    bio: "Mechanical engineer with diverse interests.",
    university_year: 4,
    major: "Mechanical Engineering",
    grad_year: 2024,
    interests: ["Reading", "Gaming", "Travel"],
    intent: "Dating",
    gender_preference: ["Female"],
    sexual_orientation: "Heterosexual",
    min_age: 21,
    max_age: 26,
    avatarFile: "p3.jpeg",
  },
  {
    email: "testuser21@northeastern.edu",
    name: "Sophia Anderson",
    birthdate: "2003-04-17",
    gender: "Female",
    pronouns: "she/her",
    bio: "Design student with passion for visual arts.",
    university_year: 2,
    major: "Design",
    grad_year: 2026,
    interests: ["Photography", "Music", "Reading"],
    intent: "Friendship",
    gender_preference: ["All"],
    sexual_orientation: "Lesbian",
    min_age: 19,
    max_age: 23,
    avatarFile: "p7.jpeg",
  },
  {
    email: "testuser22@northeastern.edu",
    name: "Tyler Johnson",
    birthdate: "2002-08-28",
    gender: "Male",
    pronouns: "he/him",
    bio: "Business student looking to network and date.",
    university_year: 3,
    major: "Business",
    grad_year: 2025,
    interests: ["Coding", "Music", "Fitness"],
    intent: "Casual Dating",
    gender_preference: ["Female"],
    sexual_orientation: "Heterosexual",
    min_age: 20,
    max_age: 24,
    avatarFile: "p6.jpeg",
  },
  {
    email: "testuser23@northeastern.edu",
    name: "Olivia Taylor",
    birthdate: "2001-01-11",
    gender: "Female",
    pronouns: "she/her",
    bio: "CS major seeking serious relationship.",
    university_year: 4,
    major: "Computer Science",
    grad_year: 2024,
    interests: ["Coding", "Reading", "Fitness"],
    intent: "Serious Relationship",
    gender_preference: ["Male"],
    sexual_orientation: "Heterosexual",
    min_age: 22,
    max_age: 27,
    avatarFile: "p1.jpeg",
  },
  {
    email: "testuser24@northeastern.edu",
    name: "Christopher Lee",
    birthdate: "2003-11-05",
    gender: "Male",
    pronouns: "he/him",
    bio: "Freshman into gaming and tech.",
    university_year: 1,
    major: "Information Technology",
    grad_year: 2027,
    interests: ["Gaming", "Coding"],
    intent: "Friendship",
    gender_preference: ["All"],
    sexual_orientation: "Gay",
    min_age: 18,
    max_age: 21,
    avatarFile: "p9.jpeg",
  },
  {
    email: "testuser25@northeastern.edu",
    name: "Amanda White",
    birthdate: "2002-06-19",
    gender: "Female",
    pronouns: "she/her",
    bio: "Mechanical engineering student with broad interests.",
    university_year: 3,
    major: "Mechanical Engineering",
    grad_year: 2025,
    interests: ["Fitness", "Photography", "Travel"],
    intent: "Dating",
    gender_preference: ["Male", "Female"],
    sexual_orientation: "Bisexual",
    min_age: 20,
    max_age: 24,
    avatarFile: "p4.jpeg",
  },
  {
    email: "testuser26@northeastern.edu",
    name: "Brandon Harris",
    birthdate: "2001-03-09",
    gender: "Male",
    pronouns: "he/him",
    bio: "Architecture student with creative flair.",
    university_year: 4,
    major: "Architecture",
    grad_year: 2024,
    interests: ["Photography", "Music", "Travel"],
    intent: "Casual Dating",
    gender_preference: ["All"],
    sexual_orientation: "Bisexual",
    min_age: 21,
    max_age: 26,
    avatarFile: "p10.jpeg",
  },
  {
    email: "testuser27@northeastern.edu",
    name: "Victoria Moore",
    birthdate: "2003-09-13",
    gender: "Female",
    pronouns: "she/her",
    bio: "Business major into fitness and music.",
    university_year: 2,
    major: "Business",
    grad_year: 2026,
    interests: ["Fitness", "Music", "Travel"],
    intent: "Dating",
    gender_preference: ["Male"],
    sexual_orientation: "Heterosexual",
    min_age: 19,
    max_age: 23,
    avatarFile: "p2.jpeg",
  },
  {
    email: "testuser28@northeastern.edu",
    name: "Andrew Jackson",
    birthdate: "2002-07-21",
    gender: "Male",
    pronouns: "he/him",
    bio: "Civil engineer seeking study buddy or more.",
    university_year: 3,
    major: "Civil Engineering",
    grad_year: 2025,
    interests: ["Coding", "Reading", "Gaming"],
    intent: "Study Buddy",
    gender_preference: ["All"],
    sexual_orientation: "Gay",
    min_age: 20,
    max_age: 24,
    avatarFile: "p8.jpeg",
  },
  {
    email: "testuser29@northeastern.edu",
    name: "Nicole Scott",
    birthdate: "2001-10-06",
    gender: "Female",
    pronouns: "she/her",
    bio: "Design student with artistic spirit.",
    university_year: 4,
    major: "Design",
    grad_year: 2024,
    interests: ["Photography", "Music", "Travel"],
    intent: "Friendship",
    gender_preference: ["All"],
    sexual_orientation: "Pansexual",
    min_age: 21,
    max_age: 26,
    avatarFile: "p5.jpeg",
  },
  {
    email: "testuser30@northeastern.edu",
    name: "Matthew Edwards",
    birthdate: "2004-02-28",
    gender: "Male",
    pronouns: "he/him",
    bio: "IT student passionate about technology.",
    university_year: 1,
    major: "Information Technology",
    grad_year: 2027,
    interests: ["Coding", "Gaming", "Music"],
    intent: "Casual Dating",
    gender_preference: ["All"],
    sexual_orientation: "Gay",
    min_age: 18,
    max_age: 21,
    avatarFile: "p9.jpeg",
  },
];

async function uploadAvatar(userId: string, avatarPath: string): Promise<string> {
  try {
    const fileContent = fs.readFileSync(avatarPath);
    const fileName = `avatar.jpeg`;
    const filePath = `${userId}/${fileName}`;

    // Remove existing file if any (though for seed we might not need to, but good practice)
    await supabaseAdmin.storage.from("profiles").remove([filePath]);

    const { error: uploadError } = await supabaseAdmin.storage
      .from("profiles")
      .upload(filePath, fileContent, {
        contentType: "image/jpeg",
        upsert: true,
      });

    if (uploadError) {
      console.error(`Failed to upload avatar for ${userId}:`, uploadError);
      throw uploadError;
    }

    const { data } = supabaseAdmin.storage.from("profiles").getPublicUrl(filePath);
    return data.publicUrl;
  } catch (error) {
    console.error(`Error uploading avatar for ${userId}:`, error);
    // Fallback to a default or dicebear if upload fails, but for this task we want to use the samples
    return `https://api.dicebear.com/7.x/avataaars/svg?seed=${userId}`; 
  }
}

async function seedUniversity(universityData: any, usersData: any[]) {
  const passwordHash = await bcrypt.hash("password123", 12);

  const avatarsDir = path.join(__dirname, "sample_avatars");
  const avatarFiles = fs.readdirSync(avatarsDir).filter(f => f.endsWith('.jpeg') || f.endsWith('.jpg'));

  if (avatarFiles.length === 0) {
    console.warn("No sample avatars found in sample_avatars directory!");
  }

  // Ensure university exists
  const university = await prisma.universities.upsert({
    where: { slug: universityData.slug },
    update: {},
    create: {
      name: universityData.name,
      slug: universityData.slug,
      university_domains: {
        create: { domain: universityData.domain },
      },
    },
  });

  console.log(`University: ${university.name} (${university.id})`);

  for (const userData of usersData) {
    const { email, name, birthdate, gender, pronouns, bio, university_year, major, grad_year, interests, intent, gender_preference, sexual_orientation, min_age, max_age, avatarFile } = userData;

    // Check if user exists to avoid unique constraint errors on re-runs
    const existingUser = await prisma.user.findUnique({ where: { email } });
    if (existingUser) {
      console.log(`User ${email} already exists, skipping...`);
      continue;
    }

    // Create user in Prisma first to get the ID
    const user = await prisma.user.create({
      data: {
        email,
        name,
        emailVerified: true,
        accounts: {
          create: {
            providerId: "credential",
            accountId: email,
            password: passwordHash,
          },
        },
      },
    });

    // Upload Avatar
    let avatarUrl = `https://api.dicebear.com/7.x/avataaars/svg?seed=${email}`;
    if (avatarFile) {
      const specificAvatarPath = path.join(avatarsDir, avatarFile);
      if (fs.existsSync(specificAvatarPath)) {
        avatarUrl = await uploadAvatar(user.id, specificAvatarPath);
      } else {
        console.warn(`Avatar file ${avatarFile} not found for user ${name}. Using default Dicebear avatar.`);
      }
    }

    // Create Profile
    await prisma.profiles.create({
      data: {
        user_id: user.id,
        name,
        avatar_url: avatarUrl,
        birthdate: new Date(birthdate),
        gender,
        pronouns,
        bio,
        university_year,
        major,
        grad_year,
        interests,
        intent,
        gender_preference,
        sexual_orientation,
        min_age,
        max_age,
        university_id: university.id,
      },
    });

    console.log(`Created user: ${user.email}`);
  }
}

async function main() {
  console.log("Start seeding...");

  // Seed NJIT users
  await seedUniversity(
    { name: "New Jersey Institute of Technology", slug: "njit", domain: "njit.edu" },
    njitUsersData
  );

  // Seed Northeastern users
  await seedUniversity(
    { name: "Northeastern University", slug: "northeastern", domain: "northeastern.edu" },
    northeasternUsersData
  );

  console.log("Seeding finished.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
