export const GRADIENT = ["#FFB199", "#FF6B81", "#6C5CE7"] as const;  // soft rose to dream purple
export const PRIMARY = "#FF6B81";       // Soft Rose (main primary pink)
export const SECONDARY = "#FFD6E0";     // Blush Pink (lighter secondary)
export const ACCENT = "#6C5CE7";        // Dream Purple (accent/CTA)
export const DARK = "#1A1A1A";          // Rich Black (dark text)
export const MUTED = "#666666";         // Gray Ash (muted text)
export const BACKGROUND = "#FAFAFA";    // Whisper White (background)
export const SUCCESS = "#00B894";       // Mint Green (success)
export const WARNING = "#FFBA08";       // keep your yellow warning as is
export const DANGER = "#D63031";        // Crimson Red (danger)
