export const GRADIENT = ["#B28DFF", "#9F6BFF", "#8E44FD"] as const; // Medium Lavender to Electric Violet
export const PRIMARY = "#9F6BFF";      // Vibrant Lavender (main primary)
export const SECONDARY = "#D3B8FF";    // Soft Plum (complementary secondary)
export const ACCENT = "#8E44FD";       // Violet Accent (strong CTA)
export const DARK = "#1A1A1A";         // Rich Black
export const MUTED = "#666666";        // Gray Ash
export const BACKGROUND = "#F4F0FF";   // Faint Lilac (still purple-leaning)
export const SUCCESS = "#55EFC4";      // Mint Green
export const WARNING = "#FFBA08";      // Golden Yellow
export const DANGER = "#D63031";       // Crimson Red
